name: geocat_comp_build
channels:
  - conda-forge
dependencies:
  - python>=3.8, <3.11
  - cftime
  - eofs
  - geocat-datafiles  # for tests
  - geocat-f2py
  - netcdf4  # for tests
  - - parameterized  # for tests
  - pytest  # for tests
  - pytest-cov  # for tests
  - pip
  - pip:
    - git+https://github.com/Unidata/MetPy.git
    - git+https://github.com/numpy/numpy.git
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - git+https://github.com/hgrecco/pint.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/xarray-contrib/cf-xarray.git
    - git+https://github.com/xarray-contrib/xskillscore.git
