name: Upstream-dev CI
on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  upstream-dev:
    name:  upstream-dev-py310
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: conda_setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geocat_comp_upstream
          channel-priority: strict
          miniconda-version: "latest"
          python-version: "3.10"
          channels: conda-forge

      - name: Install select upstream dependencies
        run: |
          pip install git+https://github.com/Unidata/MetPy.git
          pip install git+https://github.com/numpy/numpy.git
          pip install git+https://github.com/dask/dask.git
          pip install git+https://github.com/dask/distributed.git
          pip install git+https://github.com/hgrecco/pint.git
          pip install git+https://github.com/pydata/xarray.git
          pip install git+https://github.com/xarray-contrib/cf-xarray.git
          pip install git+https://github.com/xarray-contrib/xskillscore.git

      - name: Install conda dependencies
        run: |
          conda env update --file build_envs/upstream-dev-environment.yml

      - name: Install geocat-comp
        run: |
          python -m pip install . --no-deps

      - name: conda list
        run: |
          conda list

      - name: Running Tests
        run: |
          python -m pytest test -v --cov=./geocat/comp --cov-report=xml
