name: yapf
on:
  push:
    branches-ignore:
      - main
  pull_request:
  pull_request_target:
    
jobs:
  yapf_formatting:
    if: |
      contains(github.event.head_commit.message, 'trigger_yapf') || 
      contains(github.event.head_commit.message, 'trigger_actions')
    name: yapf_formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
#        with:
#          access_token: ${{ github.token }}
      - name: checkout
        uses: actions/checkout@v2
#        with:
#          token: ${{ github.token }}
#          #ref: ${{ github.head_ref }}
      - name: yapf
        run: |
          pip3 install yapf
          python3 -m yapf --in-place --recursive --style google .
      - name: git_config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'
      - if: contains(github.event.head_commit.message, 'trigger_yapf')
        name: push_yapf
        run: |
          git commit --allow-empty -am "complete_yapf"
          git push
      - if: contains(github.event.head_commit.message, 'trigger_actions')
        name: push_actions
        run: |
          git commit --allow-empty -am "complete_yapf, trigger_build_test"
          git push
